source 'https://api.berkshelf.com'

cookbook 'apt'
cookbook 'chef-solo-search', github: 'edelight/chef-solo-search'
cookbook 'users'
cookbook 'sudo'
cookbook 'ssh-hardening', github: 'TelekomLabs/chef-ssh-hardening'
cookbook 'rvm', github: 'fnichol/chef-rvm'
cookbook 'nodejs'
cookbook 'apache2'
cookbook 'postgresql'
cookbook 'database'
cookbook 'capistrano-ruby', github: 'adamkrone/chef-capistrano-ruby'
